name: build

on:
  push:
  pull_request:

jobs:
  tests:
    name: "Tests -- Python ${{ matrix.python-version }} Running On ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: pip install poetry
    - name: Turn off Virtualenvs
      run: poetry config virtualenvs.create false
    - name: Cache Dependancies
      uses: actions/cache@v1.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-
    - name: Install Dependancies
      run: poetry install
    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: "python -m tox"
